import type { Movie } from './types';
import { PlaceHolderImages } from './placeholder-images';

const imageMap = new Map(PlaceHolderImages.map((img) => [img.id, img]));

export const movies: Movie[] = [
  {
    id: 'cosmic-odyssey',
    title: 'Cosmic Odyssey',
    description: 'A thrilling journey to the edge of the universe.',
    longDescription:
      'In the year 2242, a group of intrepid explorers embarks on a perilous mission to a newly discovered galaxy. They must overcome cosmic anomalies, alien encounters, and their own inner demons to unlock the secrets of the universe and find a new home for humanity.',
    year: 2024,
    genre: ['Sci-Fi', 'Adventure'],
    cast: ['Dr. Aris Thorne', 'Captain Eva Rostova', 'Jax'],
    rating: 8.9,
    duration: '2h 35m',
    thumbnailUrl: imageMap.get('poster-1')?.imageUrl || '',
    heroImageUrl: imageMap.get('hero-1')?.imageUrl || '',
    cardImageHint: imageMap.get('poster-1')?.imageHint || '',
    heroImageHint: imageMap.get('hero-1')?.imageHint || '',
  },
  {
    id: 'whispering-woods',
    title: 'Whispering Woods',
    description: 'An ancient forest holds a dark secret.',
    longDescription:
      'When a young botanist ventures into the fabled Whispering Woods, she discovers a realm where nature is alive and sentient. But as she delves deeper, she uncovers a malevolent force that threatens to consume not only the forest but the entire world.',
    year: 2023,
    genre: ['Fantasy', 'Horror'],
    cast: ['Elara', 'The Forest Spirit', 'Lord Malakor'],
    rating: 8.2,
    duration: '1h 58m',
    thumbnailUrl: imageMap.get('poster-2')?.imageUrl || '',
    heroImageUrl: imageMap.get('hero-2')?.imageUrl || '',
    cardImageHint: imageMap.get('poster-2')?.imageHint || '',
    heroImageHint: imageMap.get('hero-2')?.imageHint || '',
  },
  {
    id: 'city-of-shadows',
    title: 'City of Shadows',
    description: 'A detective hunts a killer in a rain-slicked metropolis.',
    longDescription:
      'In a perpetually dark and raining city, grizzled detective Jake Corrigan is on the trail of a phantom-like serial killer. As he navigates the corrupt underworld, he must confront his past to stop the killer before they strike again.',
    year: 2024,
    genre: ['Thriller', 'Noir'],
    cast: ['Jake Corrigan', 'Isabella Monet', 'The Alchemist'],
    rating: 9.1,
    duration: '2h 10m',
    thumbnailUrl: imageMap.get('poster-3')?.imageUrl || '',
    heroImageUrl: imageMap.get('hero-3')?.imageUrl || '',
    cardImageHint: imageMap.get('poster-3')?.imageHint || '',
    heroImageHint: imageMap.get('hero-3')?.imageHint || '',
  },
  {
    id: 'the-last-empress',
    title: 'The Last Empress',
    description: 'A tale of power, betrayal, and sacrifice in ancient times.',
    longDescription:
      "The epic story of the last empress of a fallen dynasty. Faced with invasion and internal strife, she must make impossible choices to protect her people and preserve her culture's legacy.",
    year: 2022,
    genre: ['Drama', 'History'],
    cast: ['Empress Xian', 'General Wei', 'The Chancellor'],
    rating: 8.5,
    duration: '2h 45m',
    thumbnailUrl: imageMap.get('poster-4')?.imageUrl || '',
    heroImageUrl: imageMap.get('hero-4')?.imageUrl || '',
    cardImageHint: imageMap.get('poster-4')?.imageHint || '',
    heroImageHint: imageMap.get('hero-4')?.imageHint || '',
  },
  {
    id: 'echoes-of-love',
    title: 'Echoes of Love',
    description: 'Two souls find each other across time.',
    longDescription:
      "A mysterious old photograph connects a modern-day architect with a woman from the 1920s. Through a series of supernatural events, they form a bond that transcends time, but their love is threatened by the very fabric of reality.",
    year: 2023,
    genre: ['Romance', 'Fantasy'],
    cast: ['Leo', 'Clara', 'The Watchmaker'],
    rating: 7.9,
    duration: '2h 5m',
    thumbnailUrl: imageMap.get('poster-5')?.imageUrl || '',
    heroImageUrl: imageMap.get('hero-5')?.imageUrl || '',
    cardImageHint: imageMap.get('poster-5')?.imageHint || '',
    heroImageHint: imageMap.get('hero-5')?.imageHint || '',
  },
  {
    id: 'zero-point',
    title: 'Zero Point',
    description: 'A superhero must save the world from an existential threat.',
    longDescription:
      'When a reality-warping villain begins to erase existence itself, the veteran superhero "Apex" must assemble a team of new and old allies to fight a war for the very concept of a future.',
    year: 2024,
    genre: ['Action', 'Sci-Fi'],
    cast: ['Apex', 'Kid Comet', 'Dr. Oblivion'],
    rating: 8.8,
    duration: '2h 20m',
    thumbnailUrl: imageMap.get('poster-6')?.imageUrl || '',
    heroImageUrl: imageMap.get('hero-6')?.imageUrl || '',
    cardImageHint: imageMap.get('poster-6')?.imageHint || '',
    heroImageHint: imageMap.get('hero-6')?.imageHint || '',
  },
  {
    id: 'the-giggle-gang',
    title: 'The Giggle Gang',
    description: 'A group of friends on a quest for the ultimate prank.',
    longDescription:
      "The Giggle Gang, a quartet of mischievous animated animals, embarks on an adventure to win the legendary 'Guffaw-a-Thon' trophy. Along the way, they learn about friendship, teamwork, and the true meaning of fun.",
    year: 2023,
    genre: ['Animation', 'Comedy'],
    cast: ['Barnaby Bear', 'Penelope Penguin', 'Ferdinand Frog'],
    rating: 7.5,
    duration: '1h 30m',
    thumbnailUrl: imageMap.get('poster-7')?.imageUrl || '',
    heroImageUrl: imageMap.get('hero-7')?.imageUrl || '',
    cardImageHint: imageMap.get('poster-7')?.imageHint || '',
    heroImageHint: imageMap.get('hero-7')?.imageHint || '',
  },
  {
    id: 'beneath-the-surface',
    title: 'Beneath the Surface',
    description: 'Something ancient has awoken in the deep.',
    longDescription:
      'A deep-sea research team breaches a previously undiscovered trench, accidentally awakening a dormant creature of immense power. As it rises to the surface, the team must warn a disbelieving world before it\'s too late.',
    year: 2022,
    genre: ['Horror', 'Sci-Fi'],
    cast: ['Dr. Elena Vance', 'Commander Riggs', 'The Leviathan'],
    rating: 7.8,
    duration: '1h 45m',
    thumbnailUrl: imageMap.get('poster-8')?.imageUrl || '',
    heroImageUrl: imageMap.get('hero-8')?.imageUrl || '',
    cardImageHint: imageMap.get('poster-8')?.imageHint || '',
    heroImageHint: imageMap.get('hero-8')?.imageHint || '',
  },
  {
    id: 'sundown-riders',
    title: 'Sundown Riders',
    description: 'A classic tale of justice in the Old West.',
    longDescription:
      'When a ruthless land baron terrorizes a small frontier town, a mysterious stranger with a quick draw and a dark past is their only hope. He must confront the baron\'s gang and his own history to bring peace to the valley.',
    year: 2021,
    genre: ['Western'],
    cast: ['The Drifter', 'Sheriff Miller', 'Bartholomew Black'],
    rating: 8.1,
    duration: '2h 15m',
    thumbnailUrl: imageMap.get('poster-9')?.imageUrl || '',
    heroImageUrl: imageMap.get('hero-9')?.imageUrl || '',
    cardImageHint: imageMap.get('poster-9')?.imageHint || '',
    heroImageHint: imageMap.get('hero-9')?.imageHint || '',
  },
  {
    id: 'fist-of-the-dragon',
    title: 'Fist of the Dragon',
    description: 'He will fight for his master\'s honor.',
    longDescription:
      'After his master is murdered by a rival dojo, a young martial artist enters a deadly underground tournament to seek vengeance and restore honor to his school. His journey will test his skills, his spirit, and his loyalty.',
    year: 2023,
    genre: ['Action', 'Drama'],
    cast: ['Kenji', 'Master Chen', 'The Iron Claw'],
    rating: 8.4,
    duration: '1h 50m',
    thumbnailUrl: imageMap.get('poster-10')?.imageUrl || '',
    heroImageUrl: imageMap.get('hero-10')?.imageUrl || '',
    cardImageHint: imageMap.get('poster-10')?.imageHint || '',
    heroImageHint: imageMap.get('hero-10')?.imageHint || '',
  },
];

export const genres = [
  ...new Set(movies.flatMap((movie) => movie.genre)),
].sort();
